### ISSUE TITLE
Improve manpage

### ISSUE THREAD

**Issue by Zearin** [alecthomas/devtodo2#15]
The manpage doesn’t really explain any options more than `todo2 --help`.  

* But what are “grafting”, “reparenting”, and how are they different?  
* If no `.todo2` file exists, how do you start one?  (Easy enough to guess; just use `todo2 --add "Some new task"`.  But it should be documented, right?)

**Comment by alecthomas** [comment]
This is a good point (and sorry about the belated reply).

**Comment by Zearin** [comment]
Glad you're back! 

So, are you still developing this? Can you improve the manpage?

**Comment by alecthomas** [comment]
Yes, but it is relatively low priority. PRs welcome!
