### ISSUE TITLE
Migration ?

### ISSUE THREAD

**Issue by Pawamoy** [alecthomas/devtodo2#16]
Hi, sorry to bother and thank you very much for your app, but I just can't understand how to migrate my old .todo files to the new JSON version. I tried `todo2 --legacy-file=.todo --file=.todo2` or just `todo2 -a something`, or `todo2 --import .todo -a something`, and nothing worked, .todo2 just contains something and .todo is still XML.

**Comment by alecthomas** [comment]
Thanks for reporting this, it seems there may have been some change in Go's handling of XML struct tags. It should work now, and the usage is automatic. You shouldn't have to do anything or specify any arguments.

**Comment by Pawamoy** [comment]
Thank you very much for your quick fix !
