### ISSUE TITLE
Everything is sorted in reverse order

### ISSUE THREAD

**Issue by dead10ck** [alecthomas/devtodo2#19]
It seems that everything gets sorted in reverse order.

```sh
$ todo
  2.to ip
+ 1.to domain
    + 1.from domain
          3.related domain
          2.nameserver
          1.whois nameserver click
```

Even when sorted by a different parameter:

```sh
$ todo -A --order=text
  2.to ip
+ 1.to domain
    + 1.from domain
          1.whois nameserver click
          3.related domain
          2.nameserver
```

I'm not sure if this is intended or not, but if it is not, it would be nice to have an option to sort in ascending order, instead of descending.

**Comment by mpinloz** [comment]
The application sorts the list by priority and with this change the priority is being sorted wrong. Maybe it would be better if it was sorted by creation date by default. And with the sort flag it would print the list by priority if no other option is selected. 

![captura de pantalla de 2017-07-14 19-39-44](https://user-images.githubusercontent.com/29802178/28223571-3d3eb9b6-68cc-11e7-8d92-e24ca911e7db.png)
