### ISSUE TITLE
Purge option?

### ISSUE THREAD

**Issue by rwyc-devon** [alecthomas/devtodo2#22]
devtodo1 had a `--purge` option which I found handy. Any chance of implementing this here?

**Comment by alecthomas** [comment]
Yeah, that would be simple to add.

**Comment by rwyc-devon** [comment]
thanks!

**Comment by rwyc-devon** [comment]
it complains if I don't specify a parameter. I was expecting a default of 0s (the help message implies this too)

**Comment by alecthomas** [comment]
Alas, that is ambiguous for the flag parser and is this unsupported.

**Comment by rwyc-devon** [comment]
ah, too bad. that's fine
