### ISSUE TITLE
The executable only finds the task list when you're standing in your home directory. 

### ISSUE THREAD

**Issue by DenLilleMand** [alecthomas/devtodo2#32]
Right now it just looks in the directory you are in, so it is assumed that the to do list is always being executed from the home directory, or that you are maintaining several you have separate lists e.g. using it inside all of your projects, it gives you less clutter.  

Obviously this is useful, but i don't think this idea comes across usability wise, generally i think its cleaner to just have one file, and then spend time enhancing the graft feature to support this better. 

I was thinking of making a option(command line and config file) that enables multiple to do lists(acts like it does now), but have it disabled and home as default.

**Comment by alecthomas** [comment]
This is intentional. DevTodo is designed for per-directory task lists. If you want a single list you can use `todo2 --file=$HOME/.todo2`.

**Comment by alecthomas** [comment]
If you want to add a flag like `--global` I'd be okay with that, but the default is the desired behaviour.
