### ISSUE TITLE
Edit a task inserts the index in the task text

### ISSUE THREAD

**Issue by mpinloz** [alecthomas/devtodo2#36]
To edit a task it's necessary to inform the task id. But there isn't control to avoid insert this id in the text of the task.

The workflow to reproduce it is this:

![captura de pantalla de 2017-07-08 09-48-52](https://user-images.githubusercontent.com/29802178/27983849-1de92bd2-63c7-11e7-9089-f2a6ecdeebdd.png)

**Comment by DenLilleMand** [comment]
Yeah i noticed this error as well. @alecthomas is really busy, but he seems happy to receive PR's and gives good feedback. @mpinloz do you wan't to fix it, or are you looking for someone to do it?

**Comment by mpinloz** [comment]
Sure! I will launch the PR as soon as I could.
